import type { ProductFixture } from "./types";

// Dates and relative labels form one static visual example as of Sep 14, 2:30 PM.
// No device-clock calculation or expiration service is part of this feature.

export const products: ProductFixture[] = [
  {
    id: "yogurt-soon",
    name: "Greek yogurt",
    brand: "Valley Kitchen",
    categoryLabel: "Dairy",
    barcode: "7801234567890",
    categoryIcon: "milk",
    openedAtLabel: "Sep 12, 8:30 AM",
    lifetimeLabel: "3 days after opening",
    expirationLabel: "Sep 15, 8:30 AM",
    remainingLabel: "18 hours left",
    status: "soon",
    urgencyRank: 10,
    trust: "trusted",
    reminderLabel: "2 hours before",
  },
  {
    id: "pesto-expired",
    name: "Fresh basil pesto",
    brand: "Casa Verde",
    categoryLabel: "Sauces",
    barcode: "7802345678901",
    categoryIcon: "jar",
    openedAtLabel: "Sep 7, 1:15 PM",
    lifetimeLabel: "5 days after opening",
    expirationLabel: "Sep 12, 1:15 PM",
    remainingLabel: "Expired 2 days ago",
    status: "expired",
    urgencyRank: 0,
    trust: "trusted",
    reminderLabel: "Reminder completed",
  },
  {
    id: "oat-milk-fresh",
    name: "Barista oat drink",
    brand: "North Mill",
    categoryLabel: "Drinks",
    barcode: "7803456789012",
    categoryIcon: "bottle",
    openedAtLabel: "Sep 14, 9:00 AM",
    lifetimeLabel: "7 days after opening",
    expirationLabel: "Sep 21, 9:00 AM",
    remainingLabel: "7 days left",
    status: "fresh",
    urgencyRank: 30,
    trust: "trusted",
    reminderLabel: "1 day before",
  },
  {
    id: "sauce-unknown",
    name: "Homemade chili sauce",
    brand: "",
    categoryLabel: "Condiments",
    barcode: "7804567890123",
    categoryIcon: "jar",
    openedAtLabel: "Sep 13, 7:40 PM",
    remainingLabel: "Lifetime unavailable",
    status: "unknown",
    urgencyRank: 90,
    trust: "unverified",
    reminderLabel: "No reminder",
  },
];

// Extra representative entries make Home scroll beyond one portrait screen. All values are
// display fixtures; they do not imply a production inventory size or expiration calculation.
export const homeProducts: ProductFixture[] = [
  ...products,
  {
    ...products[1],
    id: "passata-expired",
    name: "Tomato passata",
    brand: "Orto",
    barcode: "7805678901234",
    openedAtLabel: "Sep 8, 2:30 PM",
    expirationLabel: "Sep 13, 2:30 PM",
    remainingLabel: "Expired yesterday",
    urgencyRank: 1,
  },
  {
    ...products[0],
    id: "ricotta-soon",
    name: "Fresh ricotta",
    brand: "La Fattoria",
    barcode: "7806789012345",
    openedAtLabel: "Sep 11, 6:30 PM",
    expirationLabel: "Sep 14, 6:30 PM",
    remainingLabel: "4 hours left",
    urgencyRank: 9,
  },
  {
    ...products[0],
    id: "almond-butter-soon",
    name: "Almond butter",
    brand: "Nut Grove",
    barcode: "7807890123456",
    categoryLabel: "Spreads",
    categoryIcon: "jar",
    openedAtLabel: "Sep 12, 2:30 PM",
    expirationLabel: "Sep 15, 2:30 PM",
    remainingLabel: "1 day left",
    urgencyRank: 11,
  },
  {
    ...products[0],
    id: "tapenade-soon",
    name: "Olive tapenade",
    brand: "Maison Olive",
    barcode: "7808901234567",
    categoryLabel: "Condiments",
    categoryIcon: "jar",
    openedAtLabel: "Sep 13, 2:30 PM",
    expirationLabel: "Sep 16, 2:30 PM",
    remainingLabel: "2 days left",
    urgencyRank: 12,
  },
  {
    ...products[2],
    id: "coconut-milk-fresh",
    name: "Coconut milk",
    brand: "Palm House",
    barcode: "7809012345678",
    openedAtLabel: "Sep 12, 2:30 PM",
    expirationLabel: "Sep 19, 2:30 PM",
    remainingLabel: "5 days left",
    urgencyRank: 31,
  },
  {
    ...products[2],
    id: "pickles-fresh",
    name: "Pickled cucumbers",
    brand: "Green Jar",
    barcode: "7800123456789",
    categoryLabel: "Condiments",
    categoryIcon: "jar",
    openedAtLabel: "Sep 8, 2:30 PM",
    lifetimeLabel: "14 days after opening",
    expirationLabel: "Sep 22, 2:30 PM",
    remainingLabel: "8 days left",
    urgencyRank: 32,
  },
  {
    ...products[2],
    id: "miso-fresh",
    name: "White miso paste",
    brand: "Kome",
    barcode: "7801123456789",
    categoryLabel: "Sauces",
    categoryIcon: "jar",
    openedAtLabel: "Sep 12, 2:30 PM",
    lifetimeLabel: "14 days after opening",
    expirationLabel: "Sep 26, 2:30 PM",
    remainingLabel: "12 days left",
    urgencyRank: 33,
  },
  {
    ...products[2],
    id: "salsa-fresh",
    name: "Salsa verde",
    brand: "Casa Verde",
    barcode: "7802123456789",
    categoryLabel: "Sauces",
    categoryIcon: "jar",
    openedAtLabel: "Sep 11, 2:30 PM",
    expirationLabel: "Sep 18, 2:30 PM",
    remainingLabel: "4 days left",
    urgencyRank: 34,
  },
  {
    ...products[3],
    id: "tahini-unknown",
    name: "Sesame tahini",
    brand: "Sun Seed",
    barcode: "7803123456789",
    categoryLabel: "Spreads",
    remainingLabel: "Lifetime unavailable",
    urgencyRank: 91,
  },
];

export const emptyHomeProducts: ProductFixture[] = [];
export const noSoonHomeProducts = homeProducts.filter((product) => product.status !== "soon");

export const edgeProducts: ProductFixture[] = [
  {
    ...products[0],
    id: "long-name",
    name: "Extra creamy naturally fermented probiotic family yogurt",
    brand: "A very long artisan dairy brand name",
    remainingLabel: "0 hours left",
  },
  {
    ...products[3],
    id: "missing-copy",
    name: undefined,
    brand: undefined,
    categoryIcon: "food",
  },
];

export const unknownBarcode = "7809876543210";
