import type { ProductFixture } from "./types";

// Dates and relative labels form one static visual example as of Sep 14, 2:30 PM.
// No device-clock calculation or expiration service is part of this feature.

export const products: ProductFixture[] = [
  {
    id: "yogurt-soon",
    name: "Yogur griego",
    brand: "Valley Kitchen",
    quantity: "500 g",
    categoryLabel: "Lácteos",
    barcode: "7801234567890",
    categoryIcon: "milk",
    openedAtLabel: "12 sep., 08:30",
    lifetimeLabel: "3 días después de abrir",
    storageCondition: "Refrigerar bajo 4 °C",
    storageInstruction: "Mantener cerrado y usar una cuchara limpia.",
    expirationLabel: "15 sep., 08:30",
    remainingLabel: "Quedan 18 horas",
    status: "soon",
    urgencyRank: 10,
    trust: "trusted",
    reminderLabel: "2 horas antes",
  },
  {
    id: "pesto-expired",
    name: "Pesto de albahaca fresca",
    brand: "Casa Verde",
    quantity: "190 g",
    categoryLabel: "Salsas",
    barcode: "7802345678901",
    categoryIcon: "jar",
    openedAtLabel: "7 sep., 13:15",
    lifetimeLabel: "5 días después de abrir",
    storageCondition: "Refrigerar bajo 4 °C",
    storageInstruction: "Cerrar bien la tapa después de usar.",
    expirationLabel: "12 sep., 13:15",
    remainingLabel: "Venció hace 2 días",
    status: "expired",
    urgencyRank: 0,
    trust: "trusted",
    reminderLabel: "Recordatorio completado",
  },
  {
    id: "oat-milk-fresh",
    name: "Bebida de avena barista",
    brand: "North Mill",
    quantity: "1 L",
    categoryLabel: "Bebidas",
    barcode: "7803456789012",
    categoryIcon: "bottle",
    openedAtLabel: "14 sep., 09:00",
    lifetimeLabel: "7 días después de abrir",
    storageCondition: "Refrigerar bajo 4 °C",
    storageInstruction: "Guardar en posición vertical y mantener refrigerado.",
    expirationLabel: "21 sep., 09:00",
    remainingLabel: "Quedan 7 días",
    status: "fresh",
    urgencyRank: 30,
    trust: "trusted",
    reminderLabel: "1 día antes",
  },
  {
    id: "sauce-unknown",
    name: "Salsa de ají casera",
    brand: "",
    categoryLabel: "Condimentos",
    barcode: "7804567890123",
    categoryIcon: "jar",
    openedAtLabel: "13 sep., 19:40",
    storageCondition: "Conservación no verificada",
    storageInstruction: "Aún no hay una regla de apertura verificada.",
    remainingLabel: "Duración no disponible",
    status: "unknown",
    urgencyRank: 90,
    trust: "unverified",
    reminderLabel: "Sin recordatorio",
  },
];

// Extra representative entries make Home scroll beyond one portrait screen. All values are
// display fixtures; they do not imply a production inventory size or expiration calculation.
export const homeProducts: ProductFixture[] = [
  ...products,
  {
    ...products[1],
    id: "passata-expired",
    name: "Salsa de tomate",
    brand: "Orto",
    barcode: "7805678901234",
    openedAtLabel: "8 sep., 14:30",
    expirationLabel: "13 sep., 14:30",
    remainingLabel: "Venció ayer",
    urgencyRank: 1,
  },
  {
    ...products[0],
    id: "ricotta-soon",
    name: "Ricota fresca",
    brand: "La Fattoria",
    barcode: "7806789012345",
    openedAtLabel: "11 sep., 18:30",
    expirationLabel: "14 sep., 18:30",
    remainingLabel: "Quedan 4 horas",
    urgencyRank: 9,
  },
  {
    ...products[0],
    id: "almond-butter-soon",
    name: "Mantequilla de almendras",
    brand: "Nut Grove",
    barcode: "7807890123456",
    categoryLabel: "Untables",
    categoryIcon: "jar",
    openedAtLabel: "12 sep., 14:30",
    expirationLabel: "15 sep., 14:30",
    remainingLabel: "Queda 1 día",
    urgencyRank: 11,
  },
  {
    ...products[0],
    id: "tapenade-soon",
    name: "Tapenade de aceitunas",
    brand: "Maison Olive",
    barcode: "7808901234567",
    categoryLabel: "Condimentos",
    categoryIcon: "jar",
    openedAtLabel: "13 sep., 14:30",
    expirationLabel: "16 sep., 14:30",
    remainingLabel: "Quedan 2 días",
    urgencyRank: 12,
  },
  {
    ...products[2],
    id: "coconut-milk-fresh",
    name: "Leche de coco",
    brand: "Palm House",
    barcode: "7809012345678",
    openedAtLabel: "12 sep., 14:30",
    expirationLabel: "19 sep., 14:30",
    remainingLabel: "Quedan 5 días",
    urgencyRank: 31,
  },
  {
    ...products[2],
    id: "pickles-fresh",
    name: "Pepinillos en conserva",
    brand: "Green Jar",
    barcode: "7800123456789",
    categoryLabel: "Condimentos",
    categoryIcon: "jar",
    openedAtLabel: "8 sep., 14:30",
    lifetimeLabel: "14 días después de abrir",
    expirationLabel: "22 sep., 14:30",
    remainingLabel: "Quedan 8 días",
    urgencyRank: 32,
  },
  {
    ...products[2],
    id: "miso-fresh",
    name: "Pasta de miso blanco",
    brand: "Kome",
    barcode: "7801123456789",
    categoryLabel: "Salsas",
    categoryIcon: "jar",
    openedAtLabel: "12 sep., 14:30",
    lifetimeLabel: "14 días después de abrir",
    expirationLabel: "26 sep., 14:30",
    remainingLabel: "Quedan 12 días",
    urgencyRank: 33,
  },
  {
    ...products[2],
    id: "salsa-fresh",
    name: "Salsa verde",
    brand: "Casa Verde",
    barcode: "7802123456789",
    categoryLabel: "Salsas",
    categoryIcon: "jar",
    openedAtLabel: "11 sep., 14:30",
    expirationLabel: "18 sep., 14:30",
    remainingLabel: "Quedan 4 días",
    urgencyRank: 34,
  },
  {
    ...products[3],
    id: "tahini-unknown",
    name: "Tahini de sésamo",
    brand: "Sun Seed",
    barcode: "7803123456789",
    categoryLabel: "Untables",
    remainingLabel: "Duración no disponible",
    urgencyRank: 91,
  },
];

export const emptyHomeProducts: ProductFixture[] = [];
export const noSoonHomeProducts = homeProducts.filter((product) => product.status !== "soon");

export const edgeProducts: ProductFixture[] = [
  {
    ...products[0],
    id: "long-name",
    name: "Yogur familiar extra cremoso con probióticos de fermentación natural",
    brand: "Una marca artesanal de lácteos con un nombre muy largo",
    remainingLabel: "Quedan 0 horas",
  },
  {
    ...products[3],
    id: "missing-copy",
    name: undefined,
    brand: undefined,
    categoryIcon: "food",
  },
];

export const unknownBarcode = "7809876543210";
