import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
  content: { gap: 18 },
  flex: { flex: 1, gap: 5 },
  illustration: {
    height: 210,
    borderRadius: 24,
    position: "relative",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  orbit: { width: 170, height: 170, borderRadius: 85, borderWidth: 1 },
  previewCard: {
    position: "absolute",
    width: 132,
    padding: 12,
    gap: 8,
    alignItems: "center",
    borderRadius: 14,
  },
  previewLeft: { left: 18, top: 20, transform: [{ rotate: "-9deg" }] },
  previewRight: { right: 18, top: 42, transform: [{ rotate: "9deg" }] },
  cloudBubble: {
    position: "absolute",
    bottom: 14,
    width: 66,
    height: 66,
    borderRadius: 33,
    alignItems: "center",
    justifyContent: "center",
  },
  hero: { gap: 10 },
  center: { textAlign: "center" },
  form: { gap: 16 },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  textAction: { minHeight: 38, justifyContent: "center" },
  guest: {
    flexDirection: "row",
    gap: 10,
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  messageHero: {
    height: 160,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  messageIcon: {
    width: 88,
    height: 88,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ rotate: "-8deg" }],
  },
  profile: { flexDirection: "row", gap: 14, alignItems: "center" },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  syncHero: { padding: 22, borderRadius: 16, gap: 16 },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  syncNumbers: { flexDirection: "row", gap: 48 },
  accountRow: { flexDirection: "row", gap: 12, alignItems: "center" },
  smallIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
});
